name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build & Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Show Current Versions
        run: |
          cat VERSION
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Images
        run: |
          export $(cat VERSION | xargs)
          make
          make TAG=latest
      - name: List Docker Images
        run: |
          docker image ls
      - name: Push to DockerHub
        run: |
          export $(cat VERSION | xargs)
          make push-all
          make TAG=latest push-all
